# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20)),
                ('hstatus', models.CharField(max_length=10)),
                ('haddr', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20)),
                ('iaddr', models.CharField(max_length=50)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('tcpus', models.IntegerField()),
                ('tmemory', models.IntegerField()),
                ('tuuid', models.UUIDField(default=uuid.UUID('23e99556-37c7-11e8-9000-74e6e237bcec'))),
                ('tmac', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('timgName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chmapp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upasswd', models.CharField(max_length=30)),
                ('udesc', models.CharField(max_length=30)),
                ('isLogin', models.BooleanField(default=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('vtempname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chmapp.Template')),
                ('vusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chmapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chmapp.User'),
        ),
    ]
